
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.net.MalformedURLException;
import java.net.URL;

import org.junit.Test;

import pricewatcher.networking.*;

public class LibraryTest {
    @Test
    public void priceFinder() {
        URL url = null;
        try{
         url = new URL("https://www.amazon.com/Out-Shadows-Alien-Tim-Lebbon/dp/1781162689?pf_rd_p=0fc3f2c4-3ed5-4d11-9995-8d7c82394713&pd_rd_wg=GWEYA&pf_rd_r=VA2TQFKMAE2CNQ7KMVW8&ref_=pd_gw_cr_simh&pd_rd_w=NFybL&pd_rd_r=09f01764-b838-49ae-b29a-de5c9f95cae2");
        }catch(MalformedURLException e){
            new AssertionError(e);
        }
        
    }
}
